name: flutter_facebook
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  material_design_icons_flutter: ^4.0.5345
  #toast显示
  fluttertoast: ^7.0.2
  connectivity: ^0.4.8+6 #状态的网络(WiFi &移动/蜂窝)
  #全局通知
  event_bus: ^1.1.1
  provider:
  # 加载网络图片
  cached_network_image: ^2.3.1
  flutter_swiper : ^1.1.4  #轮播图
  url_launcher: ^4.0.1
  barcode_scan: 1.0.0
  geolocator: ^5.3.2+2
  xfs_flutter_utils:
    path: ../xfs_flutter_utils

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/image/
